# buildspec-dev.yml
version: 0.2

phases:
  install:
    commands:
      - echo "Installing Terraform..."
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform -version
  build:
    commands:
      - echo "Running Terraform..."
      - cd envs/dev
      - terraform init -backend-config="bucket=terraform-state-bucket-prod-7104" -backend-config="dynamodb_table=terraform-locks-prod-7104"
      - terraform apply -auto-approve
